# Generated by Django 3.0.5 on 2023-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('disease', models.CharField(max_length=30)),
                ('referencenum', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('batchnum', models.CharField(max_length=50)),
                ('dosage', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
