# Generated by Django 3.0.5 on 2023-08-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwambokadjangoProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='batchnum',
        ),
    ]
